variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Testing App"
    - yarn install
    - yarn start &
    - CI=true yarn test
    - echo "Test successfully!"
  only:
    - dev

build:
  stage: build
  image: node:14.17.3
  script:
    - echo "Start building App"
    - export NODE_OPTIONS=--max_old_space_size=4098
    - yarn install
    - CI=false yarn build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./build/ s3://ibkm-htw-frontend
  only:
    - main



