variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy

test:
  stage: test
  image: cypress/base:14.17.3
  script:
    - yarn install --frozen-lockfile
    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions
    - npx cypress cache path
    - npx cypress cache list
    - npm run cypress:verify
    # start the server, wait for it to respond, then run Cypress tests
    - NODE_ENV=test yarn test
    # print all files in "cypress" folder
    - ls -laR cypress
    # print coverage summary so that GitLab CI can parse the coverage number
    # from a string like "Statements   : 100% ( 135/135 )"
    - npx nyc report --reporter=text-summary
  artifacts:
    when: always
    paths:
      # save both cypress artifacts and coverage results
      - coverage
      - cypress/videos/*.mp4
      - cypress/screenshots/*.png
    expire_in: 10 days
  only:
    - dev

build:
  stage: build
  image: cypress/base:14.17.3
  script:
    - echo "Start building App"
    - export NODE_OPTIONS=--max_old_space_size=4098
    - yarn install
    - CI=false yarn build
    - yarn cypress verify
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - dev
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./build/ s3://ibkm-htw-frontend
  only:
    - main



