stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"
  only:
    - dev

build:
  stage: build
  image: node:14.17.3
  script:
    - echo "Start building App"
    - export NODE_OPTIONS=--max_old_space_size=4098
    - npm install
    - CI=false npx yarn build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync ./build/ s3://ibkm-htw-project
  only:
    - main



